setup-runner:
  name: Setup runner
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install runner dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r runner-packages.txt
        
