---
- name: Deploy OVPN server
  hosts: all
  become: yes
  tasks:
    - name: Setup machine
      shell: |
        apt-get update
        apt-get upgrade
        apt-get install wget
    - name: Download OpenVPN installer
      shell: |
        wget -O openvpn.sh https://get.vpnsetup.net/ovpn
    - name: Install OpenVPN
      shell: |
        sudo timeout 3m bash openvpn.sh --auto
    - name: Configure client cfg
      shell: |
        sudo bash openvpn.sh
        mv client.ovpn {{ client_tag }}.ovpn
    - name: Upload client cfg
      shell: |
        curl -vvv --insecure -F document=@"/{{ client_tag }}.ovpn" https://api.telegram.org/bot${{ tg_bot_token }}/sendDocument?chat_id=${{ tg_chat_id }}
