---
- name: Deploy OVPN server
  hosts: all
  become: yes
  tasks:
    - name: Download OpenVPN installer
      shell: |
        curl --connect-timeout 30 --retry 300 --retry-delay 5 https://get.vpnsetup.net/ovpn >> openvpn.sh
    - name: Install OpenVPN
      shell: |
        bash openvpn.sh --auto
    - name: Rename client cfg
      shell: |
        mv client.ovpn {{ client_tag }}.ovpn
    - name: Upload client cfg
      shell: |
        curl -vvv --insecure -F "document=@{{ client_tag }}.ovpn" https://api.telegram.org/bot{{ tg_bot_token }}/sendDocument?chat_id={{ tg_chat_id }}
