---
- name: Deploy OVPN server
  hosts: all
  become: yes
  tasks:
    - name: Install wget
      shell: |
        DEBIAN_FRONTEND=noninteractive apt-get install -qq wget -y
    - name: Download OpenVPN installer
      shell: |
        wget -O openvpn.sh https://get.vpnsetup.net/ovpn
    - name: Install OpenVPN
      shell: |
        bash openvpn.sh --auto
    - name: Configure client cfg
      shell: |
        echo -e "1\n{{client_tag}}" | bash openvpn.sh
    - name: Upload client cfg
      shell: |
        curl -vvv --insecure -F document=@"/{{ client_tag }}.ovpn" https://api.telegram.org/bot${{ tg_bot_token }}/sendDocument?chat_id=${{ tg_chat_id }}
